"""add dark_mode and profile_image to user_setting

Revision ID: 736c9e861584
Revises: cc0aff69eb9c
Create Date: 2026-08-12 18:41:47.265759

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = '736c9e861584'
down_revision: Union[str, None] = 'cc0aff69eb9c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###