"""add dark_mode and profile_image to user_setting

Revision ID: ff51452eee35
Revises: 736c9e861584
Create Date: 2026-08-12 18:44:11.640845

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = 'ff51452eee35'
down_revision: Union[str, None] = '736c9e861584'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_settings', sa.Column('dark_mode', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('user_settings', sa.Column('profile_image', sa.String(length=20), server_default=sa.text("'avatar_1'"), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_settings', 'profile_image')
    op.drop_column('user_settings', 'dark_mode')
    # ### end Alembic commands ###